name: FirstWorkFlow

on:
  push:
    branches:
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name : print awelcome message
        run: echo "welcome to our gihub actions wrk flow!"
      
      
    
